### ISSUE TITLE
[FEATURE] Adding GitHub Action to fetch my latest blog from Hashnode

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Pradumnasaraf#3]
### Description

Hashnode Blog Link - https://pradumnasaraf.hashnode.dev/

**Comment by KendallDoesCoding** [comment]
I believe this is done in 82999c7, please close this issue.

**Comment by Pradumnasaraf** [comment]
> I believe this is done in [82999c7](https://github.com/Pradumnasaraf/Pradumnasaraf/commit/82999c725dc43ed81fbead6fff726f1e9559d655), please close this issue.

Wooops! Thank you for notifying me.

**Comment by KendallDoesCoding** [comment]
:)
