### ISSUE TITLE
docs: visibility issue with the hashnode directing img

### ISSUE THREAD

**Issue by kumarsonsoff3** [Pradumnasaraf/Pradumnasaraf#8]
### Description

There is a visibility issue with the hashnode directing image on the profile readme. Due to its black font, it's not clearly visible in Dark mode. 

### Screenshots

![image](https://user-images.githubusercontent.com/88786642/219880117-4515a12f-a15a-4c2d-81c2-372cf0c8586a.png)

**Comment by Pradumnasaraf** [comment]
Hey, @kumarsonsoff3,

Thanks for pointing that out. I completely remove it in https://github.com/Pradumnasaraf/Pradumnasaraf/commit/5c4bd2e68094a9ca4dcd125c5f5a382b424c2814

Closing it. Thanks, again.
